### ISSUE TITLE
Visibility algo

### ISSUE THREAD

**Issue by juek** [juek/YouTubeEmbed#2]
Currently, videos are paused as soon as they protrude even a small piece out of the viewport. This is not ideal for large videos.  I'd rather go for video<->viewport intersection instead of full coverage.

**Comment by mahotilo** [comment]
Maybe like this?

https://github.com/juek/YouTubeEmbed/pull/4

**Comment by juek** [comment]
Thanks ([merged](https://github.com/juek/YouTubeEmbed/pull/4#event-2785342222))
