### ISSUE TITLE
Error in admin mode

### ISSUE THREAD

**Issue by mahotilo** [juek/YouTubeEmbed#3]
While in Admin mode, we get multiplay errors

> Uncaught TypeError: this.Player.getPlayerState is not a function

In User mode this error does not appear.

**Comment by juek** [comment]
I'll look into it – there are some stray _this and stuff anyway, we don't need.

**Comment by juek** [comment]
fixed with the [latest commits](https://github.com/juek/YouTubeEmbed/commits)
